#!usr/bin/env python3
#-*- coding:utf-8 -*-
#python pratice002
#by carson 2019.02.26

import random

computer_number=random.randint(0,99)
guess_number=input('请输入0~99之间的数')
n=5

while n>0
n-=1
if (guess_number==computer_number):
	print('you are so clever,right!')
elif (guess_number>computer_number and guess_number-computer_number>=20):
	print('you guess too big,one more!')
	n-1
