#!usr/bin/env python3
#-*- coding:utf-8 -*-
#python pratice002
#by carson 2019.02.26

import random

computer_number=random.randint(0,99)
guess_number=int(input('请输入0~99之间的数'))

while (guess_number > 99):
	print('输入的数字错误')
	guess_number=int(input('请输入0~99之间的数'))

n=5
print ('computer_number is %d'%computer_number )

while n>0:
	if (guess_number==computer_number):
		print('you are so clever,right!')
		break
	elif (guess_number - computer_number>=20):
		print('you guess too big,one more!')
		guess_number=int(input('请输入0~99之间的数'))
		n-=1
		print(n)
	elif (guess_number>computer_number):
		print('you guess bigger,one more!')
		guess_number=int(input('请输入0~99之间的数'))
		n -= 1
		print(n)
	elif (computer_number-guess_number>=20):
		print('you guess too low,one more!')
		guess_number=int(input('请输入0~99之间的数'))
		n -= 1
		print(n)
	else :
		print('you guess lower,one more!')
		guess_number=int(input('请输入0~99之间的数'))
		nn-=1
		print(n)
print ('computer_number is %d'%computer_number )
